### ISSUE TITLE
Create job with all inline specifications

### ISSUE THREAD

**Issue by jpe316** [Azure/azureml-v2-preview#121]
az ml job create --set command="pip freeze" 

AB#995458

**Comment by luzhang06** [comment]
This would be much simplified for interactive job experience which gives user lots of flexibility during their exploratory work. We need to specify what environment to use when only command is specified, ITP experience is using current environment in the container.

**Comment by rihorn2** [comment]
Command job requires compute target, environmene, and command. So minimal job is: 
az ml job create --set compute.target=azureml:rihorn-comp environment=azureml:AzureML-PyTorch-1.5-CPU:1 command="pip freeze"
With PR here, this works. https://msdata.visualstudio.com/Vienna/_git/sdk-cli-v2/pullrequest/493626

**Comment by rihorn2** [comment]
if compute target and environment were set by az defaults, then it should work with just set command. I haven't tried using az defaults for these properties

**Comment by luzhang06** [comment]
I'm thinking of the scenario of running command in an interactive session. So the environment will be user's current environment in the docker container (similar to run a local job I guess) and the compute is the one user has SSH login to. Can we support this scenario?

**Comment by rihorn2** [comment]
Then lets consider this as two separate asks:
1. Can specify all required fields with '--set' cli options and no yaml file required. This is resolved as of the above PR, so would consider this task complete.
2. Local job submit has default for compute and environment, where environment defaults to 'local' and compute is itself. A sub-question on that is how local runs log their compute -- in the request for submitting via interactive ssh, how does that look any different from a local submisison? We could ping the Azure VM local IP to get the VM details and log those if they exist, log local otherwise? Either way, I think the details of local job submisison are a separate task from the above.
